language: ruby
cache: bundler
rvm:
  - 2.5.0
script: "bundle exec rake test"
branches:
  only: source
env:
  global:
    - JEKYLL_ENV: production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  fqdn: danielnolan.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  local-dir: _site
  verbose: true
  on:
    branch: source
