language: ruby
cache: bundler
rvm:
  - 2.4.2
script: "bundle exec rake test"
branches:
  only: source
env:
  global:
    - JEKYLL_ENV: production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  local-dir: _site
  on:
    branch: source
