# Main
url:  http://danielnolan.com
title:  danielnolandotcom
description: Code and Stuff
author: Daniel Nolan

permalink: /:year/:month/:day/:title/
excerpt_link:  "Read More&hellip;"
paginate: 4
safe: false
highlighter: pygments
lsi: false
exclude: [Readme.md, .ruby-version, vendor, .ruby-gemset, Gemfile, Gemfile.lock, Rakefile, bin]
sass:
  sass_dir: _sass
  style: :compressed
kramdown:
  input: GFM

#plugins
index_pages:
  category:
    do_related: false
    title_prefix: 'Category: '

  tag:
    do_related: false
    title_prefix: 'Tag: '
