# Main
url:  http://danielnolan.com
title:  danielnolandotcom
author: Daniel Nolan


# Jekyll Config
server: true
server_port: 4000
baseurl:  /

permalink:	/:year/:month/:day/:title/
auto: true
safe: false
pygments: true
lsi: false
exclude: Readme.markdown .rvmrc Gemfile Gemfile.lock


#plugins
index_pages:
  category:
    do_related: false
    title_prefix: 'Category: '
  
  tag:
    do_related: false
    title_prefix: 'Tag: '    