# Main
url:  http://danielnolan.com
title:  danielnolandotcom
author: Daniel Nolan

permalink:	/:year/:month/:day/:title/
safe: false
pygments: true
lsi: false
exclude: [Readme.markdown, .ruby-version, .ruby-gemset, Gemfile, Gemfile.lock]

excerpt_link:  "Read More&hellip;"

#plugins
index_pages:
  category:
    do_related: false
    title_prefix: 'Category: '
  
  tag:
    do_related: false
    title_prefix: 'Tag: '    
